AWSTemplateFormatVersion: 2010-09-09
Description: The template used to create an ECS Task definition from the ECS Console.
Parameters:
  Family:
    Type: String
    Default: book-store
  DockerImageTag:
    Type: String
    Default: latest
Resources:
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - LogConfiguration:
            Options:
              awslogs-group: /ecs/book-store
              awslogs-region: eu-central-1
              awslogs-stream-prefix: ecs
            LogDriver: awslogs
            SecretOptions: []
          Name: book-store-micro
          Image: !Sub
            - "964739173525.dkr.ecr.eu-central-1.amazonaws.com/playground/book-store-micro:${Tag}"
            - Tag: !Ref DockerImageTag
          MemoryReservation: 512
          Links: []
          PortMappings:
            - ContainerPort: 8080
              HostPort: 80
              Protocol: tcp
          EntryPoint: []
          Command: []
          Environment:
            - Name: DB_HOST
              Value: books-db.c1gaylsnpdht.eu-central-1.rds.amazonaws.com
            - Name: DB_PWD
              Value: wm4xsbwfU0c3EYMWhZKt
          EnvironmentFiles: []
          MountPoints: []
          VolumesFrom: []
          Secrets: []
          ReadonlyRootFilesystem: false
          DnsServers: []
          DnsSearchDomains: []
          ExtraHosts: []
          DockerSecurityOptions: []
          DockerLabels: {}
          Ulimits: []
          HealthCheck:
            Command:
              - >-
                wget -q --spider localhost:8080/book-store/resources/health || 
                exit 1
            Interval: 300
            Timeout: 5
            Retries: 3
          SystemControls: []
          Essential: true
          Cpu: 0
      Family: !Ref Family
      NetworkMode: bridge
      TaskRoleArn: 'arn:aws:iam::964739173525:role/ecsTaskExecutionRole'
      ExecutionRoleArn: 'arn:aws:iam::964739173525:role/ecsTaskExecutionRole'
      PlacementConstraints: []
      RequiresCompatibilities:
        - EC2
      Cpu: 2 vCPU
      Memory: 1 GB
      Tags:
        - Key: 'ecs:taskDefinition:createdFrom'
          Value: ecs-console-v2
        - Key: 'ecs:taskDefinition:stackId'
          Value: !Ref 'AWS::StackId'
Outputs:
  TaskDefinitionARN:
    Description: The created task definition ARN.
    Value: !Ref ECSTaskDefinition