AWSTemplateFormatVersion: 2010-09-09
Description: The template used to create an ECS Service from the ECS Console.
Parameters:
  ECSClusterName:
    Type: String
    Default: book-store-cluster
  SecurityGroupIDs:
    Type: CommaDelimitedList
    Default: sg-a9bf33d5
  SubnetIDs:
    Type: CommaDelimitedList
    Default: 'subnet-a623bbcc,subnet-d68b5daa,subnet-badf7af6'
  VpcID:
    Type: String
    Default: vpc-33992959
  LoadBalancerType:
    Type: String
    Default: application
    AllowedValues:
      - application
      - network
    ConstraintDescription: must specify an application or network load balancer type.
  LoadBalancerName:
    Type: String
    Default: book-store-service-1-lb
Resources:
  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: book-store-cluster
      TaskDefinition: 'arn:aws:ecs:eu-central-1:964739173525:task-definition/book-store:10'
      LaunchType: EC2
      ServiceName: book-store-service-1
      DesiredCount: 2
      LoadBalancers:
        - ContainerName: book-store-micro
          ContainerPort: 8080
          LoadBalancerName: !Ref 'AWS::NoValue'
          TargetGroupArn: !Ref TargetGroup
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
    DependsOn: Listener
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: book-store-sg
      VpcId: vpc-33992959
      SecurityGroupIngress:
        - CidrIpv6: '::/0'
          FromPort: 80
          ToPort: 80
          IpProtocol: TCP
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: TCP
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: book-store-service-1-lb
      SecurityGroups:
        - sg-a9bf33d5
      Subnets:
        - subnet-a623bbcc
        - subnet-d68b5daa
        - subnet-badf7af6
      Type: application
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: book-store-service-1-trgt-grp
      VpcId: vpc-33992959
      Protocol: HTTP
      Port: 80
      HealthCheckPath: /book-store/resources/health
      TargetType: instance
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
Outputs:
  ClusterName:
    Description: The cluster used to create the service.
    Value: !Ref ECSClusterName
  ECSService:
    Description: The created service.
    Value: !Ref ECSService
  LoadBalancer:
    Description: The created load balancer.
    Value: !Ref LoadBalancer
  Listener:
    Description: The created listener.
    Value: !Ref Listener
  TargetGroup:
    Description: The created target group.
    Value: !Ref TargetGroup
