version: '2'

services:
  book-store-1:
    image: playground/book-store-micro:latest
    ports:
      - "91:8080"
    environment:
      - DB_HOST=books-db.c1gaylsnpdht.eu-central-1.rds.amazonaws.com
      - DB_PWD=wm4xsbwfU0c3EYMWhZKt
    networks:
      y-net:
        ipv4_address: 172.28.1.1

  book-store-2:
    image: playground/book-store-micro:latest
    ports:
      - "92:8080"
    environment:
      - DB_HOST=books-db.c1gaylsnpdht.eu-central-1.rds.amazonaws.com
      - DB_PWD=wm4xsbwfU0c3EYMWhZKt
    networks:
      y-net:
        ipv4_address: 172.28.1.2

networks:
  y-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
