version: '2'

services:
  book-store-1:
    build:
      context: .
    ports:
      - "8080:8080"
      - "8181:8181"
      - "4848:4848"
      - "9009:9009"
      - "9090:9090"
    environment:
      - DB_HOST=repository
      - DB_PWD=postgres
      - PAYARA_INSTANCE_NAME=node-1
      - PAYARA_ARGS=-d
    networks:
      y-net:
        ipv4_address: 172.28.1.1

  repository:
    image: postgres:13-alpine
    mem_limit: 2048m
    memswap_limit: 3072m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      y-net:
        ipv4_address: 172.28.1.3

networks:
  y-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
